site_name: TuanNgu
nav:
  - Home: index.md
  - Api:
    - "api/rooms[GET]": api/rooms.md
    - "api/guest[GET]": api/guests.md
    - "api/staffs[GET]": api/staffs.md
    - "api/schedules[GET]": api/schedules.md

theme:
  name: material