site_name: Описание сервера "Warriors"
nav:
  - Home: index.md
  - Api:
      - "warriors/list[GET]": api/warriors.md
      - "warriors_professions[GET]": api/warriors_professions.md
      - "warriors_skills[GET]": api/warriors_skills.md
  - Registration:
      - "auth/users[POST]": registration/user.md
      - "auth/users/me[POST]": registration/login.md
      - "auth/users/me[PATCH]" : registration/edit.md

theme:
 name: material

